### ISSUE TITLE
Issue with config for 'default_scopes' and 'optional_scopes' getting put into a nested array

### ISSUE THREAD

**Issue by matthewsinclair** [doorkeeper-gem/doorkeeper#763]
I've been doing some work with `doorkeeper` and I noticed that the `scope` functionality didn't appear to be working properly. 

After some investigation, I noticed that the values for `default_scopes` and `optional_scopes` were being loaded in as `[:public]' and `[[:read_user, :write_user]]` (when using the Grape+Doorkeeper example app. 

I tracked this down to the following lines:

https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L64-L70

```ruby
      def default_scopes(*scopes)
        @config.instance_variable_set('@default_scopes', OAuth::Scopes.from_array(scopes))
      end

      def optional_scopes(*scopes)
        @config.instance_variable_set('@optional_scopes', OAuth::Scopes.from_array(scopes))
      end
```

It seems that when `OAuth::Scopes.from_array(scopes)` is called, it ends up trying to add `scopes` as an array of arrays, rather than just an array. Changing the above lines to this:

```ruby
      def default_scopes(*scopes)
        @config.instance_variable_set('@default_scopes', OAuth::Scopes.from_array(scopes[0]))
      end

      def optional_scopes(*scopes)
        @config.instance_variable_set('@optional_scopes', OAuth::Scopes.from_array(scopes[0]))
      end
```

Fixed the problem, and everything now works fine with scopes. 

So, my question is, am I doing something bonkers here, or is this a bug? 

Also, is my solution (to index the `0`th element of `scopes`) the right way to fix it? Given that the method signature is using `*scopes`, then `scopes` will always be an `Array` inside those methods, won't it? And even if `scopes` is an empty `Array`, then `scopes[0]` should just return `nil`, if I understand what's going on.

**Comment by matthewsinclair** [comment]
As an update, I thought that it might have been something to do with the way that `default_scopes` and `optional_scopes` were being set in `config/doorkeeper.rb`, but sadly, that doesn't appear to be the problem.

Neither:
```
  default_scopes  :public
  optional_scopes [:read_user, :write_user]
```
nor
```
  default_scopes  :public
  optional_scopes :read_user, :write_user
```
will work for `optional_scopes` without that change above.

**Comment by tute** [comment]
`Doorkeeper::OAuth::Scopes.from_array([:a, :b])` is meant to be called with an array. A method with an argument with a splat will convert all its arguments into an array. This means that calling `optional_scopes` with arguments is the way (your second option).

```ruby
irb(main):003:0> def optional_scopes(*scopes)
irb(main):004:1>   Doorkeeper::OAuth::Scopes.from_array(scopes)
irb(main):005:1> end
irb(main):006:0> optional_scopes([:a, :b])
=> #<Doorkeeper::OAuth::Scopes:0x007fe42173c898 @scopes=["[:a, :b]"]> # bad
irb(main):007:0>
irb(main):011:0> optional_scopes(:a, :b)
=> #<Doorkeeper::OAuth::Scopes:0x007fe420b0f160 @scopes=["a", "b"]> # good
```

What problem do you see while using the `optional_scopes :read_user, :write_user` syntax?

**Comment by matthewsinclair** [comment]
In either case, I'm getting a doubled-up array coming thru. So instead of it coming thru as:
```
[:read_user, :write_user]
```
Its coming thru as:
```
[[:read_user, :write_user]]
```
And then no scope can be found (because it's inside an array).

**Comment by matthewsinclair** [comment]
Thanks for getting back to me, by the way. I'm sure I'm doing something dumb here, but the only way I could get scopes to work at all, was with the change in the first post.

**Comment by tute** [comment]
What version of doorkeeper are you using? How can I replicate your issue?

**Comment by matthewsinclair** [comment]
I'm currently working off a fork so that I could change the above lines. If I just go back to the current gem, it's 3.0.1. I was working with this project `https://github.com/sethherr/grape-doorkeeper`, which is where I started from. It was that one (fresh out of the box) that wasn't working with scopes until I made that change.

**Comment by tute** [comment]
Probably this issue belongs in there. @sethherr have you seen this?

**Comment by matthewsinclair** [comment]
Perhaps. You're right. The `config/initializers/doorkeeper.db` file [here](https://github.com/sethherr/grape-doorkeeper/blob/master/config/initializers/doorkeeper.rb#L1) and [here](https://github.com/sethherr/grape-doorkeeper/blob/master/config/initializers/doorkeeper.rb#L45) is where the issue manifests. As soon as scopes are turned on, they don't work. Without scopes, everything is fine. As I was debugging it, I noticed the "double array" issue that I described above.

**Comment by matthewsinclair** [comment]
I've cross posted it in that other repo, [here](https://github.com/sethherr/grape-doorkeeper/issues/4).

**Comment by sethherr** [comment]
@matthewsinclair - have you pulled the most recent changes from [grape-doorkeeper](https://github.com/sethherr/grape-doorkeeper/issues/3)?

I think that issue was resolved recently in https://github.com/sethherr/grape-doorkeeper/issues/3

**Comment by matthewsinclair** [comment]
Ok, I'll give that try tomorrow morning. Thanks @sethherr and @tute for the help. Much appreciated.

**Comment by sethherr** [comment]
thanks for giving me a heads up @tute

**Comment by sethherr** [comment]
I think this issue can be closed here, it's a specific problem from not using a splat (as you said earlier in this thread). Regardless, I'm pretty sure that it's an issue with grape-doorkeeper and not doorkeeper.

https://github.com/sethherr/grape-doorkeeper/commit/66db12351178da29e04b1c57244e2adb6727485a

**Comment by matthewsinclair** [comment]
Happy to close here, I will take up in the `doorkeeper-grape` thread, but for the record, reverting to the latest gem of doorkeeper and applying the change to splay the `optional_scopes *OAUTH_SCOPES` line didn't fix the issue with scopes ceasing to work at all. I'll do some investigation and post the results in `doorkeeper-grape`. Thanks for looking into it for me.

**Comment by tute** [comment]
Thank you all!
